name: CI New

on:
  push: # This now triggers on pushes to any branch
permissions:
  pull-requests: write
  contents: write

jobs:
  Run:
    uses: ./.github/workflows/run_ip.yaml
    secrets: inherit
    with:
      repo: ${{ github.repository }}
      name: ${{ EF_UART }}
      fw: true
      docs: true
      bus_wrapper: true
      pr_base: ${{ github.head_ref || github.ref_name }}
      pr_branch: "ci-ip:BUSWRAP_COMMIT"
      #pr_branch: "ci-ip-buswrap:BUSWRAP_COMMIT"
      pr_title: "ci(ip): run bus_wrap BUSWRAP_COMMIT on IP_COMMIT"
      commit_msg: "run bus_wrap(BUSWRAP_COMMIT) on IP_COMMIT"
