name: Run UVM tests

on:
  push: # This now triggers on pushes to any branch

jobs:
  Bus-Wrap:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Set variables
        run: |
          github_repo=${{ github.repository }}
          github_repo=${github_repo#*/}
          echo "BUSWRAP_PATH=./bus-wrap" >> $GITHUB_ENV
          echo "BUSWRAP_REPO=efabless/BusWrap" >> $GITHUB_ENV
          echo "IP_PATH=./ip" >> $GITHUB_ENV
          echo "IP_NAME=${github_repo}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        name: Checkout ${{ env.BUSWRAP_REPO }}
        with:
          repository: ${{ env.BUSWRAP_REPO }}
          path: ${{ env.BUSWRAP_PATH }}
      - uses: actions/checkout@v4
        name: Checkout ${{ github.repository }}
        with:
          path: ${{ env.IP_PATH }}
      - name: Execute BusWrap flow
        run: |
          ip_dir=${{ env.IP_PATH }}
          ip_name=${{ env.IP_NAME }}
          bus_wrap_dir=${{ env.BUSWRAP_PATH }}
          rm -rf ${ip_dir}/hdl//rtl/bus_wrappers
          mkdir -p ${ip_dir}/hdl//rtl/bus_wrappers
          mkdir -p ${ip_dir}/hdl//rtl/bus_wrappers/dft
          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -apb > ${ip_dir}/hdl//rtl/bus_wrappers/${ip_name}_APB.dev.v 
          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -apb -dft > ${ip_dir}/hdl//rtl/bus_wrappers/dft/${ip_name}_APB_DFT.dev.v

          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -wb > ${ip_dir}/hdl//rtl/bus_wrappers/${ip_name}_WB.dev.v 
          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -wb -dft > ${ip_dir}/hdl//rtl/bus_wrappers/dft/${ip_name}_WB_DFT.dev.v

          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -ahbl > ${ip_dir}/hdl//rtl/bus_wrappers/${ip_name}_AHBL.dev.v
          python3 $bus_wrap_dir/scripts/bus_wrap.py ${ip_dir}/${ip_name}.yaml -ahbl -dft > ${ip_dir}/hdl//rtl/bus_wrappers/dft/${ip_name}_AHBL_DFT.dev.v
      #      - name: Push output files to a branch
      #      - name: Create a pullrequest from the branch to main
